const actionTypes = {
  FETCH_QUESTIONS_START: 'FETCH_QUESTIONS_START',
  FETCH_QUESTIONS_SUCCESS: 'FETCH_QUESTIONS_SUCCESS',
  FETCH_QUESTIONS_FAILURE: 'FETCH_QUESTIONS_FAILURE',

};

export default actionTypes;