const actionTypes = {
  CHANGE_CATEGORY: 'CHANGE_CATEGORY',
  START_GAME: 'START_GAME',
  NEXT_QUESTION: 'NEXT_QUESTION',
  ADD_RESULT: 'ADD_RESULT',
  SHOW_RESULTS: 'SHOW_RESULTS',
  RESET_GAME: 'RESET_GAME',
};

export default actionTypes;